#### Matrix Operation


###### Perform the following operations on the given matrices:
###### A=[[2    -1], [​0    3​]]
###### B=[[1   ​ 2], [-3      4​]]
###### a. A+B  b. AB c. 3A−2B

In [3]:
import numpy as np

In [ ]:
A = np.array([[2,-1],[0,3]])
B = np.array([[1,2],[-3,4]])

sum_of_matrix = A + B
product_of_matrix = np.dot(A,B)
calculation_matrix = 3*A - 2*B

print("Matrix A + Matrix B =\n", sum_of_matrix)
print("Matrix A × Matrix B =\n", product_of_matrix)
print("3×Matrix A - 2×Matrix B =\n", calculation_matrix)

Matrix A + Matrix B =
 [[ 3  1]
 [-3  7]]
Matrix A × Matrix B =
 [[ 5  0]
 [-9 12]]
3×Matrix A - 2×Matrix B =
 [[ 4 -7]
 [ 6  1]]


#### Determinants and Inverses

###### Find the determinant of A. Determine whether A is invertible. If yes, calculate A−1.

In [6]:
import numpy.linalg as LA
X = np.array([[0,-1],[0,3]])
det=LA.det(X)
if det != 0:
    print("Determinant of X =", det)
    print("X is invertible")
    print("Inverse of X =\n", LA.inv(X))
else:
    print("Determinant of X =", det)
    print("X is not invertible")

Determinant of X = 0.0
X is not invertible


#### Eigenvalues and Eigenvectors

###### Compute the eigenvalues and eigenvectors of the matrix: C=[[4 1], [​−2 1]​]

In [7]:
C = np.array([[4, 1],
              [-2, 1]])

eigenvalues, eigenvectors = np.linalg.eig(C)

print("Matrix C:")
print(C)

print("\nEigenvalues of C:")
print(eigenvalues)

print("\nEigenvectors of C:")
print(eigenvectors)

Matrix C:
[[ 4  1]
 [-2  1]]

Eigenvalues of C:
[3. 2.]

Eigenvectors of C:
[[ 0.70710678 -0.4472136 ]
 [-0.70710678  0.89442719]]


###### You are given a dataset of cars with the following features:Number of cylinders (x1​)Engine ###### size in liters (x2​)Horsepower (x3)
###### car 1: x1: 4 x2: 1.5 x3: 100 and price: 20
###### car 2: x1: 6 x2: 2.0 x3: 150 and price: 30
###### Then, find the price of a car 3 with features x1: 8 x2: 3.0 x3: 200 price:?
###### Hints:
###### Represent the given dataset as a matrix equation X.T*β=y, where X is the feature matrix, β is ###### the coefficient vector, and y is the price vector
###### Compute β (the coefficients) using the normal equation: β=(X.T * X)^−1 X.T y
###### where, X.T --> transpose matrix

In [8]:
X = np.array([
    [1, 4, 1.5, 100],
    [1, 6, 2, 150]
            ])

y = np.array([20, 30])

car3 = np.array([1, 8, 3, 200])

Xt_dot_X = np.dot(X.T, X)
Xt_dot_y = np.dot(X.T, y)
beta = np.dot(np.linalg.pinv(Xt_dot_X), (Xt_dot_y))

price_car3 = np.dot(car3, beta)
print("Predicted price for car 3:", price_car3)

Predicted price for car 3: 40.00079865825058


This code predicts the price of a car using a simple linear regression approach. It starts by organizing the given data—number of cylinders, engine size, horsepower, and price—into a matrix for the features and a vector for the prices. Using the normal equation, it calculates the coefficients that best fit the data, essentially finding the line (or hyperplane) that minimizes the difference between the predicted and actual prices. Once the coefficients are computed, it uses them to estimate the price of a new car by multiplying the new car’s features with these coefficients, giving a predicted price based on the trends observed in the initial dataset.